name: Python Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      env:
        API_TOKEN: ${{ secrets.API_TOKEN }}
      run: |
        # Get the directory of the current script
        script_dir=$(python -c 'import os; print(os.path.dirname(os.path.abspath(__file__)))')

        # Construct the config path (assuming config directory is in the same level as the script)
        config_path="${script_dir}/config/urls.json" 

        # Check if the config file exists
        if [ ! -f "$config_path" ]; then
          echo "Config file not found: $config_path"
          exit 1
        fi
        pytest -v